trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    PY351_32:
      PYVERSION: 3.5.1
      PYARCH: 32
    PY351_64:
      PYVERSION: 3.5.1
      PYARCH: 64

steps:
- powershell: .\download.ps1
  displayName: 'Run the build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Python-$(PYVERSION)-$(PYARCH)'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Python-$(PYVERSION)-$(PYARCH).zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
